import * as fs from "fs";
import * as path from "path";

const BANNER = `\
// ⚡ Auto-generated by stampd — do not edit manually.
// Regenerated automatically when stampd.config.ts changes.
`;

// ─── Conversão de valor JS → tipo TypeScript inline ──────────────────────────

function indent(level: number): string {
  return "  ".repeat(level);
}

function valueToType(value: unknown, level = 0): string {
  if (typeof value === "string") return `"${value}"`;
  if (typeof value === "number") return String(value);
  if (typeof value === "boolean") return String(value);

  if (value && typeof value === "object") {
    // Platform.select marker → union dos tipos de cada plataforma
    const v = value as Record<string, unknown>;
    if (v.__platformSelect === true) {
      const opts = v.options as Record<string, unknown>;
      const variants = Object.values(opts)
        .filter((opt) => opt !== null && opt !== undefined)
        .map((opt) => valueToType(opt, level));
      const unique = [...new Set(variants)];
      return unique.join(" | ");
    }

    const entries = Object.entries(v);
    if (entries.length === 0) return "Record<string, never>";

    const props = entries.map(([key, val]) => {
      const safeKey = /^[a-zA-Z_$][\w$]*$/.test(key) ? key : `"${key}"`;
      return `${indent(level + 1)}${safeKey}: ${valueToType(val, level + 1)};`;
    });

    return `{\n${props.join("\n")}\n${indent(level)}}`;
  }

  return "unknown";
}

// ─── Geração do arquivo .d.ts ─────────────────────────────────────────────────

export function generateThemeTypes(
  tokens: Record<string, unknown>,
  lightTheme: Record<string, unknown>,
  projectRoot: string,
): void {
  const merged = { ...tokens, ...lightTheme };
  const themeType = valueToType(merged, 1);

  const content = `${BANNER}
export {};

declare global {
  namespace StyledSystem {
    interface Theme ${themeType}
  }
}
`;

  const outputPath = path.join(projectRoot, "stampd-types.d.ts");

  try {
    const existing = fs.existsSync(outputPath)
      ? fs.readFileSync(outputPath, "utf-8")
      : "";

    if (existing === content) return; // nada mudou, não escreve

    fs.writeFileSync(outputPath, content, "utf-8");
    console.log(`\x1b[36m[stampd] 📝 Tipos gerados: ${outputPath}\x1b[0m`);
  } catch (e) {
    console.warn("[stampd] Falha ao gerar typed:", e);
  }
}
